[package]
name = "tcping"
version = "1.2.4"
authors = ["lvillis<lvillis@outlook.com>"]
edition = "2021"
description = "🛠️ tcping-rs: Rust (rs) TCP Ping (tcping) Utility for Port Reachability."
license = "MIT"
repository = "https://github.com/lvillis/tcping-rs"
homepage = "https://github.com/lvillis/tcping-rs"
documentation = "https://github.com/lvillis/tcping-rs/blob/main/README.md"

[workspace]
members = [".", "bin/ref-type"]

[dependencies]
clap = { version = "4.5.23", default-features = false, features = ["std", "color", "usage", "help", "suggestions", "error-context", "derive"] }
ctrlc = { version = "3.4.5", default-features = false }
serde = { version = "1.0.214", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.132", default-features = false, features = ["std"] }
